kind: pipeline
name: default

steps:
- name: test
  image: gradle:jdk11
  commands:
  - gradle build uploadArtifacts --stacktrace
- name: upload_reports
  image: gradle:jdk11
  commands:
    - gradle uploadReports --stacktrace
  environment:
    BANDBOX_FTP_USERNAME:
      from_secret: BANDBOX_FTP_USERNAME
    BANDBOX_FTP_PASSWORD:
      from_secret: BANDBOX_FTP_PASSWORD
  when:
    branch:
    - master
    event:
    - push
    status:
      - success
      - failure