kind: pipeline
name: default

steps:
  - name: publish
    image: appleboy/drone-scp

settings:
  host:
    - bandbox.dreamhost.com
  username:
    from_secret: BANDBOX_FTP_USERNAME
  password:
    from_secret: BANDBOX_FTP_PASSWORD
  port: 22
  command_timeout: 4m
  target: ~/artifacts.acornui.com
  source:
    - build/artifacts


#- name: test
#  image: gradle:jdk11
#  commands:
#  - gradle build --stacktrace
#  environment:
#    BANDBOX_FTP_USERNAME:
#      from_secret: BANDBOX_FTP_USERNAME
#    BANDBOX_FTP_PASSWORD:
#      from_secret: BANDBOX_FTP_PASSWORD
#- name: upload_reports
#  image: gradle:jdk11
#  commands:
#    - gradle uploadReports --stacktrace
#  environment:
#    BANDBOX_FTP_USERNAME:
#      from_secret: BANDBOX_FTP_USERNAME
#    BANDBOX_FTP_PASSWORD:
#      from_secret: BANDBOX_FTP_PASSWORD
#  when:
#    branch:
#    - master
#    event:
#    - push
#    status:
#      - success
#      - failure