kind: pipeline
name: default

steps:
  - name: build-test-publish
    image: gradle:6.0-jdk8
    commands:
      - gradle build publish dokka --stacktrace --no-daemon
  - name: upload-reports
    image: appleboy/drone-scp
    settings:
      host:
        - bandbox.dreamhost.com
      username:
        from_secret: BANDBOX_FTP_USERNAME
      password:
        from_secret: BANDBOX_FTP_PASSWORD
      port: 22
      command_timeout: 4m
      target: ~/testreports.acornui.com
      source:
        - ./**/build/reports
      rm: true
      when:
        branch:
        - master
        event:
        - push
        status:
          - success
          - failure
  - name: upload-artifacts
    image: appleboy/drone-scp
    settings:
      host:
        - bandbox.dreamhost.com
      username:
        from_secret: BANDBOX_FTP_USERNAME
      password:
        from_secret: BANDBOX_FTP_PASSWORD
      port: 22
      command_timeout: 4m
      strip_components: 2
      target: ~/artifacts.acornui.com/mvn
      source:
        - build/artifacts