kind: pipeline
name: default

steps:
- name: test
  image: gradle:jdk11
  commands:
  - gradle build --stacktrace
#- name: upload_reports
#  image: gradle:jdk11
#  commands:
#    - gradle publishReports --stacktrace
#  when:
#    branch:
#    - master
#    event:
#    - push
#    status:
#      - success
#      - failure