kind: pipeline
name: default

steps:
  - name: build
    image: openjdk:8-jdk
    commands:
      - ./gradlew publish -x jsBrowserTest --stacktrace
  - name: upload-reports
    image: appleboy/drone-scp
    settings:
      host:
        - bandbox.dreamhost.com
      username:
        from_secret: BANDBOX_FTP_USERNAME
      password:
        from_secret: BANDBOX_FTP_PASSWORD
      port: 22
      command_timeout: 4m
      target: ~/testreports.acornui.com
      source:
        - ./**/build/reports
      rm: true
      when:
        branch:
          - master
        status: [ success, failure ]
  - name: upload-artifacts
    image: appleboy/drone-scp
    settings:
      host:
        - bandbox.dreamhost.com
      username:
        from_secret: BANDBOX_FTP_USERNAME
      password:
        from_secret: BANDBOX_FTP_PASSWORD
      port: 22
      command_timeout: 4m
      strip_components: 2
      target: ~/artifacts.acornui.com/mvn
      source:
        - build/artifacts
      when:
        branch:
          - master
  - name: slack-notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_ACORNBOT_WEBHOOK
      channel: acorn-bot
      template: >
        {{#success build.status}}
          Build {{build.number}} succeeded. W00t W00t!
        {{else}}
          Build {{build.number}} upload failed. Fix me please.
        {{/success}}
      when:
        status: [ success, failure ]

trigger:
  event:
    - push