name: CI

on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build
      uses: eskatos/gradle-command-action@v1
      if: "!contains(github.event.head_commit.message, 'skip-tests')"
      with:
        arguments: build --stacktrace
    - name: Upload Test Reports
      uses: actions/upload-artifact@v1
      if: always() && !contains(github.event.head_commit.message, 'skip-tests')
      with:
        name: test-reports-${{ matrix.os }}
        path: build/reports
  publish:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      # First publish locally, then test the templates, then publish to sonatype.
      - name: Publish artifacts
        run: |
          ./gradlew publishToMavenLocal -x check -s
          ./build/templates/basic/gradlew build -s
          ./gradlew publish -x check -s
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{secrets.OSSRH_USERNAME}}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{secrets.OSSRH_PASSWORD}}
          ORG_GRADLE_PROJECT_signingKeyId: ${{secrets.SIGNING_KEY_ID}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.SIGNING_PASSWORD}}
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.SIGNING_KEY}}
      - name: Upload Templates
        uses: appleboy/scp-action@v0.0.5
        with:
          host: bandbox.dreamhost.com
          username: ${{ secrets.BANDBOX_FTP_USERNAME }}
          password: ${{ secrets.BANDBOX_FTP_PASSWORD }}
          source: "build/distributions,build/templates/latest.txt"
          target: "~/artifacts.acornui.com/templates/"
          strip_components: 2