name: CI

on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # First publish locally, then test the templates, then publish to sonatype.
      - name: Publish artifacts
        run: |
          ./gradlew build testTemplates publish -s
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{secrets.OSSRH_USERNAME}}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{secrets.OSSRH_PASSWORD}}
          ORG_GRADLE_PROJECT_signingKeyId: ${{secrets.SIGNING_KEY_ID}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.SIGNING_PASSWORD}}
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.SIGNING_KEY}}
      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: "test-reports"
          path: "./*/build/reports"
      - name: Upload Templates
        uses: appleboy/scp-action@v0.0.5
        with:
          host: bandbox.dreamhost.com
          username: ${{ secrets.BANDBOX_FTP_USERNAME }}
          password: ${{ secrets.BANDBOX_FTP_PASSWORD }}
          source: "build/distributions,build/templates/latest.txt"
          target: "~/artifacts.acornui.com/templates/"
          strip_components: 2
      - name: Clear Acornui.com Version Cache
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://www.acornui.com/clearcache.php"