name: CI

on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Gradle Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build -x jsBrowserTest --stacktrace
    - name: Upload Test Reports
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test-reports-${{ matrix.os }}
        path: build/reports
  publish:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Publish artifacts
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish -PgithubToken=${{ secrets.GITHUB_TOKEN }}
