name: CI

on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build publish -x jsBrowserTest --stacktrace
    - name: bundle-test-reports
      if: always()
      run: tar -cvf build/reports.tar **/build/reports
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: upload-test-reports
        path: build/reports.tar
