name: Publish release
# Thanks to https://medium.com/@shanemyrick/publishing-to-github-packages-with-gradle-and-github-actions-4ad842634c4e
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish artifacts
        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # If we split on '/' and take the 3rd value,
        # we can get the release name.
        # | tail -c +2 to remove the leading 'v'
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3 | tail -c +2)
          echo "New version: ${NEW_VERSION}"
          ./gradlew buildTemplates publish -Pversion=${NEW_VERSION} -s
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{secrets.OSSRH_USERNAME}}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{secrets.OSSRH_PASSWORD}}
          ORG_GRADLE_PROJECT_signingKeyId: ${{secrets.SIGNING_KEY_ID}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.SIGNING_PASSWORD}}
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.SIGNING_KEY}}
      - name: Upload Templates
        uses: appleboy/scp-action@v0.0.5
        with:
          host: bandbox.dreamhost.com
          username: ${{ secrets.BANDBOX_FTP_USERNAME }}
          password: ${{ secrets.BANDBOX_FTP_PASSWORD }}
          source: "build/distributions,build/templates/release-staging.txt"
          target: "~/artifacts.acornui.com/templates/"
          strip_components: 2