name: Publish release
# Thanks to https://medium.com/@shanemyrick/publishing-to-github-packages-with-gradle-and-github-actions-4ad842634c4e
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Publish artifacts
        env:
          # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
          # If we split on '/' and take the 3rd value,
          # we can get the release name.
          run: |
            NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
            echo "New version: ${NEW_VERSION}"
            echo "Github username: ${GITHUB_ACTOR}"
            ./gradlew publish -Pversion=${NEW_VERSION} -PgithubToken=${{ secrets.GITHUB_PUBLISH_TOKEN }} -PgithubAtor=${{ GITHUB_ACTOR }}